/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/cuzn/appgroup/pkg/apis/app/v1"
	scheme "github.com/cuzn/appgroup/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AppGroupsGetter has a method to return a AppGroupInterface.
// A group's client should implement this interface.
type AppGroupsGetter interface {
	AppGroups(namespace string) AppGroupInterface
}

// AppGroupInterface has methods to work with AppGroup resources.
type AppGroupInterface interface {
	Create(*v1.AppGroup) (*v1.AppGroup, error)
	Update(*v1.AppGroup) (*v1.AppGroup, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.AppGroup, error)
	List(opts metav1.ListOptions) (*v1.AppGroupList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AppGroup, err error)
	AppGroupExpansion
}

// appGroups implements AppGroupInterface
type appGroups struct {
	client rest.Interface
	ns     string
}

// newAppGroups returns a AppGroups
func newAppGroups(c *AppV1Client, namespace string) *appGroups {
	return &appGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the appGroup, and returns the corresponding appGroup object, and an error if there is any.
func (c *appGroups) Get(name string, options metav1.GetOptions) (result *v1.AppGroup, err error) {
	result = &v1.AppGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("appgroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AppGroups that match those selectors.
func (c *appGroups) List(opts metav1.ListOptions) (result *v1.AppGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AppGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("appgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested appGroups.
func (c *appGroups) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("appgroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a appGroup and creates it.  Returns the server's representation of the appGroup, and an error, if there is any.
func (c *appGroups) Create(appGroup *v1.AppGroup) (result *v1.AppGroup, err error) {
	result = &v1.AppGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("appgroups").
		Body(appGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a appGroup and updates it. Returns the server's representation of the appGroup, and an error, if there is any.
func (c *appGroups) Update(appGroup *v1.AppGroup) (result *v1.AppGroup, err error) {
	result = &v1.AppGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("appgroups").
		Name(appGroup.Name).
		Body(appGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the appGroup and deletes it. Returns an error if one occurs.
func (c *appGroups) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("appgroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *appGroups) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("appgroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched appGroup.
func (c *appGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.AppGroup, err error) {
	result = &v1.AppGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("appgroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
