/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	appv1 "github.com/cuzn/appgroup/pkg/apis/app/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAppGroups implements AppGroupInterface
type FakeAppGroups struct {
	Fake *FakeAppV1
	ns   string
}

var appgroupsResource = schema.GroupVersionResource{Group: "app.jdos.io", Version: "v1", Resource: "appgroups"}

var appgroupsKind = schema.GroupVersionKind{Group: "app.jdos.io", Version: "v1", Kind: "AppGroup"}

// Get takes name of the appGroup, and returns the corresponding appGroup object, and an error if there is any.
func (c *FakeAppGroups) Get(name string, options v1.GetOptions) (result *appv1.AppGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(appgroupsResource, c.ns, name), &appv1.AppGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appv1.AppGroup), err
}

// List takes label and field selectors, and returns the list of AppGroups that match those selectors.
func (c *FakeAppGroups) List(opts v1.ListOptions) (result *appv1.AppGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(appgroupsResource, appgroupsKind, c.ns, opts), &appv1.AppGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &appv1.AppGroupList{ListMeta: obj.(*appv1.AppGroupList).ListMeta}
	for _, item := range obj.(*appv1.AppGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested appGroups.
func (c *FakeAppGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(appgroupsResource, c.ns, opts))

}

// Create takes the representation of a appGroup and creates it.  Returns the server's representation of the appGroup, and an error, if there is any.
func (c *FakeAppGroups) Create(appGroup *appv1.AppGroup) (result *appv1.AppGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(appgroupsResource, c.ns, appGroup), &appv1.AppGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appv1.AppGroup), err
}

// Update takes the representation of a appGroup and updates it. Returns the server's representation of the appGroup, and an error, if there is any.
func (c *FakeAppGroups) Update(appGroup *appv1.AppGroup) (result *appv1.AppGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(appgroupsResource, c.ns, appGroup), &appv1.AppGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appv1.AppGroup), err
}

// Delete takes name of the appGroup and deletes it. Returns an error if one occurs.
func (c *FakeAppGroups) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(appgroupsResource, c.ns, name), &appv1.AppGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAppGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(appgroupsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &appv1.AppGroupList{})
	return err
}

// Patch applies the patch and returns the patched appGroup.
func (c *FakeAppGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *appv1.AppGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(appgroupsResource, c.ns, name, pt, data, subresources...), &appv1.AppGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*appv1.AppGroup), err
}
